version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: cool
      MONGO_INITDB_ROOT_PASSWORD: cool
      MONGO_INITDB_DATABASE: admin
    volumes:
    - mongo_data:/home/mongodb
    - ./mongo/docker/:/docker-entrypoint-initdb.d/
    - mongo_db:/data/db

volumes:
  mongo_data:
    name: mongo_volume
  mongo_db:
    name: mongo_db_volume