{{- if .Values.imageCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
  {{- end }}